#include "mario.hpp"

#include "tap/communication/sensors/buzzer/buzzer.hpp"

#include "modm/architecture/interface/delay.hpp"

namespace songs
{
void playMarioThemesongBlocking(tap::gpio::Pwm *pwmController)
{
    using namespace tap::buzzer;
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 510);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 770);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(550);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(575);
    playNote(pwmController, 510);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(450);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(400);
    playNote(pwmController, 320);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(500);
    playNote(pwmController, 440);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 480);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(330);
    playNote(pwmController, 450);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(200);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(200);
    playNote(pwmController, 760);
    modm::delay_ms(50);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 860);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 700);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 760);
    modm::delay_ms(50);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 520);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 580);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 480);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(500);
    playNote(pwmController, 510);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(450);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(400);
    playNote(pwmController, 320);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(500);
    playNote(pwmController, 440);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 480);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(330);
    playNote(pwmController, 450);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(200);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(200);
    playNote(pwmController, 760);
    modm::delay_ms(50);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 860);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 700);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 760);
    modm::delay_ms(50);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 520);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 580);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 480);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(500);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 570);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(220);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(200);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 570);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(420);
    playNote(pwmController, 585);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(450);
    playNote(pwmController, 550);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(420);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(360);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 570);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(220);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(200);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 1020);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 760);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 720);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 680);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 620);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 650);
    modm::delay_ms(150);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 570);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(420);
    playNote(pwmController, 585);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(450);
    playNote(pwmController, 550);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(420);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(360);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 580);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 380);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(600);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 580);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(550);
    playNote(pwmController, 870);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(325);
    playNote(pwmController, 760);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(600);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 500);
    modm::delay_ms(60);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 580);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(350);
    playNote(pwmController, 660);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 500);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 430);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 380);
    modm::delay_ms(80);
    silenceBuzzer(pwmController);
    modm::delay_ms(600);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(150);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 510);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(100);
    playNote(pwmController, 660);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(300);
    playNote(pwmController, 770);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(550);
    playNote(pwmController, 380);
    modm::delay_ms(100);
    silenceBuzzer(pwmController);
    modm::delay_ms(575);
}

}  // namespace songs